variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_qt5
  - test_qt62_jammy
  - test_qt64
  - test_qt65_android
  - test_qt66
  - test_qt66_android
  - test_qt67
  - test_qt67_android
  - test_qt68
  - test_qt68_android

Test_qt5:
  stage: test_qt5
  image:
    name: "carlonluca/qt-dev:5.15.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt5
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - ./LQtUtilsTest

Test_qt62_jammy:
  stage: test_qt62_jammy
  image:
    name: "carlonluca/qt-dev:6.2.4_jammy"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - ./LQtUtilsTest

Test_qt64:
  stage: test_qt64
  image:
    name: "carlonluca/qt-dev:6.4.3"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - LD_LIBRARY_PATH=/usr/local/lib ./LQtUtilsTest

Test_qt65_android:
  stage: test_qt65_android
  image:
    name: "carlonluca/qt-dev:6.5.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - /opt/Qt-android-6.5.2/android_arm64_v8a/bin/qt-cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DQT_ANDROID_BUILD_ALL_ABIS:BOOL=ON \
      -S ../qt6;
    - cmake --build .

Test_qt66:
  stage: test_qt66
  image:
    name: "carlonluca/qt-dev:6.6.1"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - LD_LIBRARY_PATH=/usr/local/lib ./LQtUtilsTest

Test_qt66_android:
  stage: test_qt66_android
  image:
    name: "carlonluca/qt-dev:6.6.1"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - /opt/Qt-android-6.6.1/android_arm64_v8a/bin/qt-cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DQT_ANDROID_BUILD_ALL_ABIS:BOOL=ON \
      -S ../qt6;
    - cmake --build .

Test_qt67:
  stage: test_qt67
  image:
    name: "carlonluca/qt-dev:6.7.3"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - LD_LIBRARY_PATH=/usr/local/lib ./LQtUtilsTest

Test_qt67_android:
  stage: test_qt67_android
  image:
    name: "carlonluca/qt-dev:6.7.3"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - /opt/Qt-android-6.7.3/android_arm64_v8a/bin/qt-cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DQT_ANDROID_BUILD_ALL_ABIS:BOOL=ON \
      -S ../qt6;
    - cmake --build .

Test_qt68:
  stage: test_qt68
  image:
    name: "carlonluca/qt-dev:6.8.3"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - LD_LIBRARY_PATH=/usr/local/lib ./LQtUtilsTest

Test_qt68_android:
  stage: test_qt68_android
  image:
    name: "carlonluca/qt-dev:6.8.3"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - /opt/qt/6.8.3/android_arm64_v8a/bin/qt-cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DQT_ANDROID_BUILD_ALL_ABIS:BOOL=ON \
      -S ../qt6;
    - cmake --build .